adverts/urls.py
from django.conf.urls import url
from adverts.views import ad_create, upload_media, remove_uploaded_media
from .views import one_ad as view_more

urlpatterns = [
    url(r'^ad_create/$', ad_create, name='ad_create'),
    url(r'^view_more/(?P<ad_id>\d+)$', view_more, name='view_more'),
    url(r'^upload_media/$', upload_media, name='upload_media'),
    url(r'^remove_uploaded_media/$', remove_uploaded_media, name='remove_uploaded_media'),
]

ferma/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from adverts.views import index as new_advert
from ferma import settings
from main.views import index as index
from main.views import search_results as search
from companies.views import index as companies
from django.conf.urls import handler404

handler404 = ''

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='main'),
    url(r'^new_advert/$', new_advert, name='create_advert'),
    url(r'^ad/', include('adverts.urls', namespace='ad')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^search_results/$', search, name='search'),
    url(r'^companies/', include('companies.urls', namespace='companies')),
    url(r'^news/', include('news.urls', namespace='news'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url

from .views import news_list

urlpatterns = [
    url(r'^$', news_list, name='news_list')
]

adverts/models.py
# coding=utf-8
from __future__ import unicode_literals
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.exceptions import ValidationError
from django.db import models


# Create your models here.
class CreateNewAdvert(models.Model):
    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'

    name = models.CharField(verbose_name='Name', max_length=255, null=True)
    email = models.CharField(verbose_name='Email', max_length=255, null=True)
    title = models.CharField(max_length=255, verbose_name='Заголовок', null=True)
    media = models.ManyToManyField('Media', verbose_name='Изображения', blank=True)
    advert_type = models.CharField(max_length=255, verbose_name='Тип объявления',
                                   choices=(
                                       ('sell', 'Продаю'), ('buy', 'Куплю'), ('change', 'Меняю'), ('rent', 'Аренда'),
                                       ('offers', 'Услуги')))
    categories = models.CharField(max_length=255, verbose_name='Категория',
                                  choices=(
                                      ('stock_raising', 'Животноводство'), ('aviculture', 'Птицеводство'),
                                      ('pisciculture', 'Рыбоводство'), ('plant_growing', 'Растениеводство'),
                                      ('apiculture', 'Пчеловодство'), ('stern', 'Корма'),
                                      ('veterinary_drugs', 'Ветиренарные препараты'), ('the_property', 'Недвижимость'),
                                      ('production', 'Продукция'), ('equipment', 'Сельхоз техника и оборудование'),
                                      ('fertilizer', 'Удобрения')))
    text = RichTextUploadingField()
    date = models.DateField("Date", auto_now_add=True, null=True, blank=True)
    is_active = models.BooleanField(default=False, verbose_name='Подтверждено')
    agree_with_rules = models.BooleanField(default=False, verbose_name='Согласен с правилами')

    def __unicode__(self):
        return 'ad object'
        # return self.title


class Media(models.Model):
    class Meta:
        verbose_name = 'Медиа'
        verbose_name_plural = 'Медиа'

    media_file = models.FileField(verbose_name='Медиа файл')

    def get_absolute_url(self):
        return self.media_file.url

    def save(self, *args, **kwargs):
        super(Media, self).save(*args, **kwargs)

    def __unicode__(self):
        return str(self.media_file)

templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Ferma.kg</title>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript">
        function CleanFunc(obj) {
            $(obj).parent().css({
                "display": "none"
            });
            $(obj).parent().siblings().css({
                "margin-left": 0,
                "width": 100 + '%',
                "max-width": 100 + '%',
                "padding-left": 0
            });
            $(obj).parent().siblings().find('.more_block').css({
                'padding-left': 0
            })
        }
    </script>
</head>
<body>
<div class="mobile_hamburger"><a href="#" class="closed"><i class="fa fa-bars"></i></a></div>
<div class="mobile_menu" id="mobile_menu">
    <ul class="menu_list">
        <li><a href="#">главная</a></li>
        <li><a href="#">компании</a></li>
        <li><a href="#">новости</a></li>
    </ul>
</div>
<div class="white_back">
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded ferma_nav">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="#">Главная<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="#">Новости<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="#">Компании<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <a class="navbar-brand m-auto" href="#"><img src="{% static 'img/logo.png' %}" alt=""></a>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link ad_advert" href="#">Добавить объявление<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <form action="#">
                            <input type="search" placeholder="Поиск">
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
{% block slider %}
    <div class="container-fluid main_slider">
        {% for i in slider %}
            <div class="slider_item">
                <div class="slider_item_caption container">
                    <div class="caption_title">{{ i.title }}</div>
                    <div class="caption_subtitle">{{ i.description }}</div>
                </div>
                <img src="{{ i.image.url }}" alt="">
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block content %}
{% endblock %}
<div class="container-fluid footer_container">
    <div class="container footer">
        <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-12 left_side"></div>
            <div class="footer_content col-md-8 col-sm-12 col-xs-12 m-auto">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_title">Айыл-чарба</div>
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li><a href="">Главная</a></li>
                                    <li><a href="">Компании</a></li>
                                    <li><a href="">Новости</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_title">Контакты</div>
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li>+996 (700) 222 932</li>
                                    <li>Whats App</li>
                                    <li>Viber</li>
                                    <li>Telegram</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li class="nav-item">
                                        <a class="nav-link ad_advert" href="#">Добавить объявление<span class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="nav-item">
                                        <form action="#">
                                            <input type="search" placeholder="Поиск">
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12 right_side"></div>
        </div>
    </div>
</div>
<script src="//cdn.ckeditor.com/4.7.1/basic/ckeditor.js"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/companies.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}

templates/footer.html
<div class="container-fluid footer_container">
    <div class="container footer">
        <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-12 left_side"></div>
            <div class="footer_content col-md-8 col-sm-12 col-xs-12 m-auto">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_title">Айыл-чарба</div>
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li><a href="">Главная</a></li>
                                    <li><a href="">Компании</a></li>
                                    <li><a href="">Новости</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_title">Контакты</div>
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li>+996 (700) 222 932</li>
                                    <li>Whats App</li>
                                    <li>Viber</li>
                                    <li>Telegram</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li class="nav-item">
                                        <a class="nav-link ad_advert" href="#">Добавить объявление<span class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="nav-item">
                                        <form action="#">
                                            <input type="search" placeholder="Поиск">
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12 right_side"></div>
        </div>
    </div>
</div>
<script src="//cdn.ckeditor.com/4.7.1/basic/ckeditor.js"></script>
<script src="js/main.js"></script>
</body>
</html>

templates/header.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/main.css">
    <title>Ferma.kg</title>
    <script src="js/jquery-3.1.1.min.js"></script>
    <script type="text/javascript">
        function CleanFunc(obj) {
            $(obj).parent().css({
                "display": "none"
            });
            $(obj).parent().siblings().css({
                "margin-left": 0,
                "width": 100 + '%',
                "max-width": 100 + '%',
                "padding-left": 0
            });
            $(obj).parent().siblings().find('.more_block').css({
                'padding-left': 0
            })
        }
    </script>
</head>
<body>
<div class="mobile_hamburger"><a href="#" class="closed"><i class="fa fa-bars"></i></a></div>
<div class="mobile_menu" id="mobile_menu">
    <ul class="menu_list">
        <li><a href="#">главная</a></li>
        <li><a href="#">компании</a></li>
        <li><a href="#">новости</a></li>
    </ul>
</div>
<div class="white_back">
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded ferma_nav">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="#">Главная<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="#">Новости<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="#">Компании<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <a class="navbar-brand m-auto" href="#"><img src="img/logo.png" alt=""></a>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link ad_advert" href="#">Добавить объявление<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <form action="#">
                            <input type="search" placeholder="Поиск">
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load banner_filter %}
{% block content %}
    <div class="container main_content">
        <div class="row">
            <div class="col-md-2 col-sm-12 col-xs-12 left_side">
                <div class="left_panel sticky-top">
                    <form action="#" class="search"><input type="search" id="mobile_input" placeholder="Поиск"></form>
                    <div class="panel_title">объявления</div>
                    <ul id="left_menu_list">
                        <li><a href="#all_ads" class="active" role="tab" data-toggle="tab">Все объявления</a></li>
                        <li><a href="#sell" role="tab" data-toggle="tab">продаю</a></li>
                        <li><a href="#buy" role="tab" data-toggle="tab">куплю</a></li>
                        <li><a href="#change" role="tab" data-toggle="tab">меняю</a></li>
                        <li><a href="#rent" role="tab" data-toggle="tab">аренда</a></li>
                        <li><a href="#offers" role="tab" data-toggle="tab">услуги</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8 col-sm-12 col-xs-12 posts_container">
                <div class="ads_category_filter">
                    <ul class="category_list">
                        <li><a href="#"><img src="{% static 'img/sheep.svg' %}" alt=""><span
                                class="category_name">Животноводство</span></a></li>
                        <li><a href="#"><img src="{% static 'img/chicken.svg' %}" alt=""><span
                                class="category_name">Птицеводство</span></a></li>
                        <li><a href="#"><img src="{% static 'img/fish.svg' %}" alt=""><span
                                class="category_name">Рыбоводство</span></a>
                        </li>
                        <li><a href="#"><img src="{% static 'img/vegetables.svg' %}" alt=""><span
                                class="category_name">Растениводство</span></a></li>
                        <li><a href="#"><img src="{% static 'img/bees.svg' %}" alt=""><span
                                class="category_name">Пчеловодство</span></a>
                        </li>
                        <li><a href="#"><img src="{% static 'img/food.png' %}" alt=""><span
                                class="category_name">Корма</span></a></li>
                        <li><a href="#"><img src="{% static 'img/pills.svg' %}" alt=""><span
                                class="category_name">Ветеринарные препараты</span></a></li>
                        <li><a href="#"><img src="{% static 'img/buildings.svg' %}" alt=""><span
                                class="category_name">Недвижимость</span></a>
                        </li>
                        <li><a href="#"><img src="{% static 'img/products.svg' %}" alt=""><span class="category_name">Продукция</span></a>
                        </li>
                        <li><a href="#"><img src="{% static 'img/tractor.svg' %}" alt=""><span class="category_name">Сельхозтехника и оборудования</span></a>
                        </li>
                        <li><a href="#"><img src="{% static 'img/fertilizer.svg' %}" alt=""><span
                                class="category_name">Удобрения</span></a></li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="all_ads">
                        {% for i in all_ads %}
                            {% if not forloop.counter|divisibleby:4 %}
                                <div class="post clearfix">
                                    <div class="post_image col-md-4 col-sm-4 col-xs-12 no_padding">
                                        <img src="{{ i.media.first.media_file.url }}" alt="" onerror="CleanFunc(this)">
                                    </div>
                                    <div class="post_describe col-md-8 col-sm-8 col-xs-12 no_padding">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="#">Объявления</a></li>
                                            <li class="breadcrumb-item"><a href="#">{{ i.get_advert_type_display }}</a>
                                            </li>
                                            <li class="breadcrumb-item active">{{ i.get_categories_display }}</li>
                                        </ol>
                                        <div class="date_block">
                                            <span>{{ i.date }}</span>
                                        </div>
                                        <div class="post_title">
                                            <h2>{{ i.title }}</h2>
                                        </div>
                                        <div class="post_describe_text">
                                            <p>{{ i.text | safe }}</p>
                                        </div>
                                        <div class="more_block">
                                            <a href="{% url 'ad:view_more' i.id %}" class="show_more">показать</a>
                                            <a href="#" class="reply"><i class="fa fa-reply" aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <img src="{{ i.image.url }}" alt="">
                            {% endif %}
                        {% endfor %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-center mt-4">
                                <li class="page-item">
                                    <a class="page-link" href="#" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="tab-pane fade show" id="sell">
                        {% for i in sell %}
                            <div class="post clearfix">
                                <div class="post_image col-md-4 col-sm-4 col-xs-12 no_padding">
                                    <img src="{{ i.media.first.media_file.url }}" alt="" onerror="CleanFunc(this)">
                                </div>
                                <div class="post_describe col-md-8 col-sm-8 col-xs-12 no_padding">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="#">Объявления</a></li>
                                        <li class="breadcrumb-item"><a href="#">{{ i.get_advert_type_display }}</a></li>
                                        <li class="breadcrumb-item active">{{ i.get_categories_display }}</li>
                                    </ol>
                                    <div class="date_block">
                                        <span>{{ i.date }}</span>
                                    </div>
                                    <div class="post_title">
                                        <h2>{{ i.title }}</h2>
                                    </div>
                                    <div class="post_describe_text">
                                        <p>{{ i.text | safe }}</p>
                                    </div>
                                    <div class="more_block">
                                        <a href="{% url 'ad:view_more' i.id %}" class="show_more">показать</a>
                                        <a href="#" class="reply"><i class="fa fa-reply" aria-hidden="true"></i></a>
                                    </div>
                                </div>
                            </div>
                            {% if forloop.counter|divisibleby:3 %}
                                {% for b in banner %}
                                    <div class="banner_post clearfix"><a href="#"><img
                                            src="{{ b.image.url }}"
                                            alt=""></a></div>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center mt-4">
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="col-md-2 col-sm-2 col-xs-3 right_side">
        <div class="right_banner sticky-top">
            <a href="#"><img src="{% static 'img/banner2.png' %}" alt=""></a>
        </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/new_advert.html
//= template/header.html
//= template/slider.html
<div class="container main_content">
    <div class="row">
        <div class="col-md-2 col-sm-2 col-xs-12 left_side">
            <div class="left_panel sticky-top">
            </div>
        </div>
        <div class="col-md-8 col-sm-8 col-xs-12 form_container">
            <form action="#" method="POST">
                <div class="form_row"><label for="name">Ваше имя</label><input type="text" id="name"></div>
                <div class="form_row"><label for="email">Ваш Email</label><input type="email" id="email"></div>
                <div class="form_row"><label for="title">Введите заголовок</label><input type="text" id="title"></div>
                <div class="form_row"><label for="advert_type">Тип объявления</label><select name="" id="advert_type">
                    <option value="#">All</option>
                </select></div>
                <div class="form_row"><label for="advert_category">Выберите категорию</label><select name=""
                                                                                                     id="advert_category">
                    <option value="#">All</option>
                </select></div>
                <div class="form_row"><label>Выберите картинку не более 1 мб</label><label for="advert_images"
                                                                                           class="advert_images">Выберите
                    файл</label><input type="file" id="advert_images"></div>
                <div class="form_row"><textarea name="ad_text" id="ad_text" cols="30" rows="10"
                                                placeholder="Введите текст объявления"></textarea></div>
                <div class="form_row"><input type="checkbox" id="agree_with_rules"><label for="agree_with_rules">Я
                    согласен с <a href="#">правилами</a></label></div>


                <input type="submit" placeholder="Отправить">
            </form>
        </div>
        <div class="col-md-2 col-sm-2 col-xs-3 right_side">
            <div class="right_banner sticky-top">
            </div>
        </div>
    </div>
</div>
<script src="js/advert.js"></script>
//= template/footer.html

templates/one_ad_page.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container main_content">
        <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-12 left_side">
            </div>
            <div class="col-md-8 col-sm-12 col-xs-12 posts_container">
                <div class="one_ad_post clearfix">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Объявления</a></li>
                        <li class="breadcrumb-item"><a href="#">{{ ad.get_advert_type_display }}</a></li>
                        <li class="breadcrumb-item active">{{ ad.get_categories_display }}</li>
                    </ol>
                    <div class="date_block">
                        <span>{{ ad.date }}</span>
                    </div>
                    <div class="post_images no_padding">
                        {% for i in media %}
                            <div class="img_rect"><img src="{{ i.media_file.url }}" alt="" onerror="CleanFunc(this)">
                            </div>
                        {% endfor %}
                    </div>
                    <div class="post_describe no_padding">
                        <div class="post_title">
                            <h2>{{ ad.title }}</h2>
                        </div>
                        <div class="post_describe_text">
                            <p>{{ ad.text |safe }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-3 right_side">
                <div class="right_banner sticky-top">
                    <a href="#"><img src="{% static 'img/banner2.png' %}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}